[package]
name = "zjit"
version = "0.0.0"
edition = "2021"        # Rust 2021 edition to compile with
rust-version = "1.58.0" # Minimally supported rust version
publish = false         # Don't publish to crates.io

[lib]
crate-type = ["staticlib"]

[dependencies]
